name: catalog-app - Build and deploy React application
on:
  push:
    branches:
    - main
    #paths:
    #- frontends/micro-frontend/catalog-app**
# Permission to support Azure login using OIDC
permissions:
  id-token: write
env:  
  STORAGE_ACCOUNT_NAME: stmedev
  STORAGE_CONTAINER: catalog-app
  WORKING_DIRECTORY: frontends/micro-frontend/catalog-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout to the branch
      uses: actions/checkout@v3
    - 
      name: Install Node.js
      uses: actions/setup-node@v3
      with: 
        node-version: 16
    -
      name: Npm install
      working-directory: ${{ env.WORKING_DIRECTORY }} 
      run: npm install webpack-merge webpack-config-single-spa-react-ts
    -
      name: Build application
      working-directory: ${{ env.WORKING_DIRECTORY }} 
      run: npm run build:webpack
    - 
      name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: coffee-app-dist
        path: |
            ${{ env.WORKING_DIRECTORY }}/dist/

  deploy:
    runs-on: ubuntu-latest
    # Set Git Environments
    environment: dev
    needs: build
    steps:
    - # Only need to azure-oidc-login 
      uses: actions/checkout@v3
      with:
        sparse-checkout: |
          .github   
    - 
      name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: coffee-app-dist
        path: dist
    # - 
    #   name: Test 2
    #   shell: bash
    #   run: |
    #     pwd
    #     ls -al
    - 
      name: Azure Login using OIDC
      uses: ./.github/workflows/composite/azure-oidc-login
      with:
        tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client_id: ${{ secrets.AZURE_CLIENT_ID }} # See Readme for the correct Client Id to reference
    - 
      name: Deploy to Azure Container App
      uses: azure/CLI@v1
      with:
        inlineScript: >
          az storage blob upload-batch --overwrite true -d ${{ env.STORAGE_CONTAINER }} --account-name ${{ env.STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} -s dist
    - 
      name: logout
      run: >
        az logout
