name: me-coffee-api - Build and deploy .NET API to container app
on:
  push:
    branches:
    - main
  #  paths:
  #  - Services/Coffee**
# Permission to support Azure login using OIDC
permissions:
  id-token: write
env:  
  CONTAINER_APP_RESOURCE_GROUP_NAME: MelloGee
  CONTAINER_APPS_ENVIRONMENT: env-me-dev-eastus
  CONTAINER_APP_CONTAINER_NAME: container-main
  CONTAINER_APP_NAME: me-coffee-api
  CONTAINER_REGISTRY_LOGIN_SERVER: registry.hub.docker.com
  DOCKER_FILE_PATH: Services/Coffee/Coffee.API/Dockerfile
  PROJECT_NAME_FOR_DOCKER: coffeeapi
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout to the branch
      uses: actions/checkout@v3
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - 
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    - 
      name: Login to Docker Hub container registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Build and push image to Docker Hub registry
      uses: docker/build-push-action@v2
      with:
        push: true 
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    # Set Git Environments
    environment: dev
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Azure Login using OIDC
      uses: ./.github/workflows/composite/azure-oidc-login
      with:
        tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client_id: ${{ secrets.AZURE_CLIENT_ID }} # See Readme for the correct Client Id to reference
    - name: Deploy to Azure Container App
      uses: azure/CLI@v1
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} 

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: logout
      run: >
        az logout
